/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "servidorweb.h"


void
servidor_rpc_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	char terminal_rpc_1_user;
	int terminal_rpc_1_request;
	char terminal_rpc_1_timestamp;
	char terminal_rpc_1_filename;

#ifndef	DEBUG
	clnt = clnt_create (host, SERVIDOR_RPC, SERVIDOR_RPCVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = terminal_rpc_1(terminal_rpc_1_user, terminal_rpc_1_request, terminal_rpc_1_timestamp, terminal_rpc_1_filename, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	servidor_rpc_1 (host);
exit (0);
}
