/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "servidorweb.h"

bool_t
xdr_convertir_request (XDR *xdrs, convertir_request *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->timestamp))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->operation_code))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->data, ~0))
		 return FALSE;
	return TRUE;
}
