/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "servidorweb.h"
#include <stdbool.h>

bool_t
terminal_rpc_1_svc(int request, char *timestamp, char *user, int *result,  struct svc_req *rqstp)
{
  bool_t retval;
  
  switch(request){
    // Imprimimos el mensaje correspondiente a cada request
    case '0':
      printf("%s REGISTER %s\n", user, timestamp);
      break;
    case '1':
      printf("%s UNREGISTER %s\n", user, timestamp);
      break;
    case '2':
      printf("%s CONNECT %s\n", user, timestamp);
      break;
    case '3':
      printf("%s PUBLISH %s\n", user, timestamp);
      break;
    case '4':
      printf("%s DELETE %s\n", user, timestamp);
      break;  
    case '5':
      printf("%s LIST_USERS %s\n", user, timestamp);
      break;
    case '6':
      printf("%s LIST_CONTENT %s\n", user, timestamp);
      break;
    case '7':
      printf("%s DISCONNECT %s\n", user, timestamp);
      break;
  }
  retval = TRUE;
  return retval;
}

int
servidor_rpc_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
  xdr_free (xdr_result, result);

  /*
   * Insert additional freeing code here, if needed
   */

  return 1;
}
