/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVIDORWEB_H_RPCGEN
#define _SERVIDORWEB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct convertir_request {
	long timestamp;
	int operation_code;
	char *data;
};
typedef struct convertir_request convertir_request;

#define STRING_PROG 0x20000001
#define STRING_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define vocales 1
extern  int * vocales_1(request *, CLIENT *);
extern  int * vocales_1_svc(request *, struct svc_req *);
#define first 2
extern  char ** first_1(request *, CLIENT *);
extern  char ** first_1_svc(request *, struct svc_req *);
#define convertir 3
extern  char ** convertir_1(convertir_request *, CLIENT *);
extern  char ** convertir_1_svc(convertir_request *, struct svc_req *);
extern int string_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define vocales 1
extern  int * vocales_1();
extern  int * vocales_1_svc();
#define first 2
extern  char ** first_1();
extern  char ** first_1_svc();
#define convertir 3
extern  char ** convertir_1();
extern  char ** convertir_1_svc();
extern int string_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_convertir_request (XDR *, convertir_request*);

#else /* K&R C */
extern bool_t xdr_convertir_request ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVIDORWEB_H_RPCGEN */
