/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVIDORWEB_H_RPCGEN
#define _SERVIDORWEB_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct terminal_rpc_1_argument {
	char *user;
	int request;
	char *timestamp;
	char *filename;
};
typedef struct terminal_rpc_1_argument terminal_rpc_1_argument;

#define SERVIDOR_RPC 99
#define SERVIDOR_RPCVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define terminal_rpc 1
extern  enum clnt_stat terminal_rpc_1(char *, int , char *, char *, int *, CLIENT *);
extern  bool_t terminal_rpc_1_svc(char *, int , char *, char *, int *, struct svc_req *);
extern int servidor_rpc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define terminal_rpc 1
extern  enum clnt_stat terminal_rpc_1();
extern  bool_t terminal_rpc_1_svc();
extern int servidor_rpc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_terminal_rpc_1_argument (XDR *, terminal_rpc_1_argument*);

#else /* K&R C */
extern bool_t xdr_terminal_rpc_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVIDORWEB_H_RPCGEN */
